# Site settings
author: Darren Lou
title: daz_code
header-img: img/home-bg.png
email: darren.lou@gmail.com
copyright_name: Darren Lou
description: > # this means to ignore newlines until "baseurl:"
  UX Engineering the Dream
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: _darrenlou
github_username:  darrendaz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
